name: Build the latest container
on:
  push:
    branches:
      - production
jobs:
  build:
    name: Build
    uses: ./.github/workflows/job--build-containers.yml
    with:
      BASE_TAG: latest
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
