name: Build and tag container
on:
  workflow_call:
    inputs:
      BASE_TAG:
        description: The base of the tag to build
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_TOKEN:
        required: true
jobs:
  build-and-tag-container:
    name: Build & Tag
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Build CIMonitor image
        run: docker build --target production --tag rickvdstaaij/move-to-dropbox:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push docker image to the hub
        run: docker push rickvdstaaij/move-to-dropbox:latest
